const wordList=[
  {"word":"cedid","hint":"Yeni, modern anlamında eski Türkçe kelime."},
  {"word":"mürur","hint":"Geçiş, akış anlamında eski kullanım."},
  {"word":"tefekkür","hint":"Düşünme, derin düşünce."},
  {"word":"mütemadiyen","hint":"Sürekli, aralıksız."},
  {"word":"intizar","hint":"Bekleme, sabırla bekleme."},
  {"word":"mağrur","hint":"Kibirli, kendini beğenmiş."},
  {"word":"mürşit","hint":"Rehber, yol gösteren kişi."},
  {"word":"zahiren","hint":"Görünüşte, dıştan."},
  {"word":"süregiden","hint":"Devam eden, süre gelen."},
  {"word":"tecelli","hint":"Ortaya çıkma, belirgin olma."},
  {"word":"ihtimalen","hint":"Muhtemelen, olabilir anlamında."},
  {"word":"müteferrika","hint":"Farklı, değişik, çeşitli."},
  {"word":"müsamaha","hint":"Hoşgörü, anlayış gösterme."},
  {"word":"teşebbüs","hint":"Girişim, çaba."},
  {"word":"mahzur","hint":"Engel, sakınca."},
  {"word":"mecazî","hint":"Gerçek dışı, mecaz anlam."},
  {"word":"istihkak","hint":"Hakkını alma, kazanılmış hak."},
  {"word":"mutasavvıf","hint":"Tasavvufla uğraşan kişi."},
  {"word":"münasip","hint":"Uygun, elverişli."},
  {"word":"münzevi","hint":"Toplumdan uzak yaşayan kişi."},
  {"word":"fesat","hint":"Bozuculuk, kötülük."},
  {"word":"mürteci","hint":"Eskiyi savunan, muhafazakâr."},
  {"word":"gaflet","hint":"Dikkatsizlik, dalgınlık."},
  {"word":"istifham","hint":"Soru sorma, sorgulama."},
  {"word":"tezyin","hint":"Süsleme, güzelleştirme."},
  {"word":"müstakil","hint":"Bağımsız, kendi başına."},
  {"word":"zuhur","hint":"Ortaya çıkma, görünme."},
  {"word":"ihata","hint":"Çevreleme, kuşatma."},
  {"word":"mükellef","hint":"Görevli, sorumlu kişi."},
  {"word":"tevazu","hint":"Alçakgönüllülük."},
  {"word":"münbit","hint":"Verimli, bereketli toprak."},
  {"word":"müteşekkil","hint":"Düzenli, sistemli yapı."},
  {"word":"tekaddüm","hint":"İlerleme, gelişme."},
  {"word":"rukün","hint":"Temel unsur, köşe taşı."},
  {"word":"muhteva","hint":"İçerik, kapsam."},
  {"word":"tevcih","hint":"Yönlendirme, atama."},
  {"word":"muhafaza","hint":"Koruma, saklama."},
  {"word":"mesuliyet","hint":"Sorumluluk."},
  {"word":"teskin","hint":"Sakinleştirme, yatıştırma."},
  {"word":"mütehassıs","hint":"Uzman, alanında yetkin kişi."},
  {"word":"muhterem","hint":"Saygıdeğer, değerli."},
  {"word":"teşvik","hint":"Cesaretlendirme, özendirme."},
  {"word":"mefkure","hint":"İdeal, amaç."},
  {"word":"müteessir","hint":"Üzgün, üzülmüş."},
  {"word":"mütalaa","hint":"Görüş, düşünce açıklama."},
  {"word":"istihza","hint":"Alay, küçümseme."},
  {"word":"mücerret","hint":"Soyut, somut olmayan."},
  {"word":"teferruat","hint":"Detaylar, ayrıntılar."},
  {"word":"muallim","hint":"Öğretmen, eğitimci."},
  {"word":"tecessüs","hint":"Merakla araştırma, casusluk anlamında."},
  {"word":"muhtasar","hint":"Kısa ve öz."},
  {"word":"muvaffakiyet","hint":"Başarı, istenen sonuç."},
  {"word":"tezyif","hint":"Değerini düşürme, küçültme."},
  {"word":"mütehammil","hint":"Dayanıklı, katlanabilen."},
  {"word":"teaddüt","hint":"Çoğalma, artış."},
  {"word":"mütekabil","hint":"Karşılıklı, birbirine uygun."},
  {"word":"tevellüt","hint":"Doğum, ortaya çıkış."},
  {"word":"muvazenet","hint":"Denge, ölçülülük."},
  {"word":"muhasara","hint":"Kuşatma, çevreleme."},
  {"word":"müteşekkir","hint":"Minnettar, teşekkür eden."},
  {"word":"müessir","hint":"Etkili, tesirli."},
  {"word":"tefsir","hint":"Açıklama, yorum."},
  {"word":"istinad","hint":"Dayanak, kaynak."},
  {"word":"mütemayil","hint":"Eğilimli, meyilli."},
  {"word":"müstağni","hint":"Bağımsız, başkasına muhtaç olmayan."},
  {"word":"tevafuk","hint":"Uygunluk, rastlantı sonucu uyum."},
  {"word":"müteşebbis","hint":"Girişimci, iş yapan kişi."},
  {"word":"teheccüd","hint":"Gece ibadeti."},
  {"word":"müstebit","hint":"Zorba, baskıcı."},
  {"word":"şifahen","hint":"Sözlü olarak."},
  {"word":"çehre","hint":"Yüz, surat."},
  {"word":"gönül","hint":"Kalp, iç duygu."},
  {"word":"düşkün","hint":"Bakımı zor durumda olan, perişan."},
  {"word":"sükûn","hint":"Huzur, sessizlik."},
  {"word":"çözümsüz","hint":"Çare bulunamayan."},
  {"word":"bağdaş","hint":"Dizleri çaprazlayarak oturma."},
  {"word":"öngörü","hint":"İleriye dönük tahmin."},
  {"word":"çağrışım","hint":"Bir düşüncenin başka bir düşünceyi akla getirmesi."},
  {"word":"ışık","hint":"Aydınlatıcı enerji."},
  {"word":"çağdaş","hint":"Aynı döneme ait, modern."},
  {"word":"çözümleme","hint":"Analiz etme."},
  {"word":"bağış","hint":"Karşılıksız verilen şey."},
  {"word":"gürültü","hint":"Rahatsız edici ses."},
  {"word":"yöneliş","hint":"Bir tarafa doğru eğilim."},
  {"word":"çığır","hint":"Yol, yöntem."},
  {"word":"öykü","hint":"Kısa edebi anlatı türü."},
  {"word":"sürükleyici","hint":"İlgi uyandıran, merak ettiren."},
  {"word":"düşünce","hint":"Fikir, zihin ürünü."},
  {"word":"gözetim","hint":"Kontrol altında tutma."},
  {"word":"içgüdü","hint":"Doğuştan gelen davranış eğilimi."},
  {"word":"çıkış","hint":"Dışarıya yönelen yol."},
  {"word":"özveri","hint":"Kendinden fedakârlık etme."}
];